### ISSUE TITLE
How to prepare wd format dataset?

### ISSUE THREAD

**Issue by pixeli99** [sayakpaul/instructpix2pix-sdxl#5]
Perhaps this question is a bit silly, but in order to use your repo for training, I would like to ask how to convert the current original zip file, such as shard-00.zip, into `wd format` data. If you could give me some simple advice, I would be very grateful.

**Comment by sayakpaul** [comment]
Hi, thanks for your interest!

This repo is still WIP. 

Regarding your question, tagging the expert @patil-suraj.

**Comment by pixeli99** [comment]
Okay, I see. Thank you very much for your reply~

**Comment by pixeli99** [comment]
@sayakpaul 
After modifying a small part of the code for data reading, I can train. However, I am puzzled that using bs=1 consumes 77GB of GPU memory. Similarly, my input image is also 256*256. I don't know if this is normal or not.
```bash
accelerate launch new_train.py \
    --pretrained_model_name_or_path=$MODEL_DIR \
    --pretrained_vae_model_name_or_path=madebyollin/sdxl-vae-fp16-fix \
    --resolution=256 --random_flip \
    --per_gpu_batch_size=1 --gradient_accumulation_steps=4 \
    --max_train_steps=15000 \
    --checkpointing_steps=2500 --checkpoints_total_limit=1 \
    --learning_rate=5e-05 --lr_warmup_steps=0 \
    --conditioning_dropout_prob=0.05 \
    --seed=42 \
    --val_image_url_or_path=./diffusion_re/sa_10746077.jpg \
    --validation_prompt="make it in japan" \
    --report_to=wandb \
    --enable_xformers_memory_efficient_attention \
    --mixed_precision="fp16"
```
I did not enable ema because it would cause OOM. I think this may be abnormal. I did not enable deep speed or other operations, so I want to know the memory usage during your training.😭
![image](https://github.com/sayakpaul/instructpix2pix-sdxl/assets/46072190/d2f8a466-7b29-4a06-8a94-09bf37af0d76)

**Comment by sayakpaul** [comment]
Sorry, we won't be able to look into this problem right now as I mentioned this repo is still WIP.

**Comment by pixeli99** [comment]
> Sorry, we won't be able to look into this problem right now as I mentioned this repo is still WIP.

Thank you for letting me know, and I apologize for any inconvenience caused. Please do keep me updated when there are developments or when it's a good time to revisit this. I appreciate your efforts and understanding. Have a great day!

**Comment by GX77** [comment]
@pixeli99 May I ask if you have solved the problem with EMA?
